[project]
name = "mptorch"
dynamic = ["dependencies", "version"]
license = {text = "GPL-3.0"}
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.12"

[build-system]
requires = ["setuptools", "torch", "ninja"]
build-backend = "setuptools.build_meta"

[project.urls]
Repository = "https://github.com/mptorch/mptorch"
Issues = "https://github.com/mptorch/mptorch/issues"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
version = {attr = "mptorch.__version__"}

[tool.setuptools.packages.find]
where = ["."]

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu132"

[tool.uv.pip]
extra-index-url = ["https://download.pytorch.org/whl/cu132"]
index-strategy = "unsafe-best-match"
no-build-isolation = true