// Compiling, caching and launching the MPS backend's Metal kernels (see
// metal_runtime.h). This is the backend's only Objective-C++ file, and it
// is compiled without ARC, as torch's own .mm files are: the objects it
// keeps (the pipelines) are retained once and live as long as the process,
// and the rest are autoreleased inside a pool.

#include "metal_runtime.h"
#include "mps_metal_sources.h" // generated by setup.py (embed_metal_sources)

#include <ATen/mps/MPSDevice.h>
#include <ATen/mps/MPSStream.h>
#include <c10/util/Exception.h>

#import <Metal/Metal.h>

#include <mutex>
#include <unordered_map>
#include <vector>

namespace mptorch_mps
{
  namespace
  {

    const char *kernel_source(KernelSource s)
    {
      return s == KernelSource::Gemm ? metal_sources::gemm : metal_sources::quantize;
    }

    const char *kernel_name(KernelSource s)
    {
      return s == KernelSource::Gemm ? "mpt_gemm" : "mpt_quantize";
    }

    // Compiles one instantiation into a pipeline. Returns nil and fills
    // `error` on failure, rather than raising, because a C++ exception must
    // not unwind through the autorelease pool.
    id<MTLComputePipelineState> compile(KernelSource source, const std::string &tail,
                                        std::string &error)
    {
      const std::string text = std::string(metal_sources::prelude) +
                               "#line 1 \"<instantiation>\"\n" + tail +
                               kernel_source(source);
      @autoreleasepool
      {
        id<MTLDevice> device = at::mps::MPSDevice::getInstance()->device();
        MTLCompileOptions *options = [[MTLCompileOptions new] autorelease];
        // Safe math, as prelude.metal's pragmas also ask: the fast casts'
        // Veltkamp split is exact only if nothing reassociates or contracts
        // it (bit_helper.h, MPTORCH_FAST_CAST). The language version is left
        // at the newest the OS has; the headers need C++17's `if constexpr`.
        if (@available(macOS 15.0, *))
        {
          options.mathMode = MTLMathModeSafe;
          options.mathFloatingPointFunctions = MTLMathFloatingPointFunctionsPrecise;
        }
        else
        {
          // The pre-15 spelling of the same request, deprecated only once
          // mathMode replaced it.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
          options.fastMathEnabled = NO;
#pragma clang diagnostic pop
        }
        NSError *err = nil;
        id<MTLLibrary> library =
            [[device newLibraryWithSource:[NSString stringWithUTF8String:text.c_str()]
                                  options:options
                                    error:&err] autorelease];
        if (library == nil)
        {
          error = err ? err.localizedDescription.UTF8String : "unknown error";
          return nil;
        }
        id<MTLFunction> function =
            [[library newFunctionWithName:[NSString stringWithUTF8String:kernel_name(source)]]
                autorelease];
        id<MTLComputePipelineState> pipeline =
            [device newComputePipelineStateWithFunction:function error:&err];
        if (pipeline == nil)
          error = err ? err.localizedDescription.UTF8String : "unknown error";
        return pipeline; // retained: the cache owns it for the process's life
      }
    }

    // One pipeline per (source, tail), compiled on first use. The mutex is
    // held across a compile, so two threads meeting a new instantiation at
    // once compile it once.
    id<MTLComputePipelineState> pipeline_for(KernelSource source, const std::string &tail)
    {
      static std::mutex mutex;
      static std::unordered_map<std::string, id<MTLComputePipelineState>> cache;
      std::string key(1, static_cast<char>('0' + static_cast<int>(source)));
      key += tail;
      std::lock_guard<std::mutex> lock(mutex);
      auto it = cache.find(key);
      if (it != cache.end())
        return it->second;
      std::string error;
      id<MTLComputePipelineState> pipeline = compile(source, tail, error);
      TORCH_CHECK(pipeline != nil, "mptorch: compiling the MPS kernel ", kernel_name(source),
                  " failed. This is a bug in mptorch; the instantiation was\n", tail,
                  "\nand the Metal compiler said:\n", error);
      cache.emplace(std::move(key), pipeline);
      return pipeline;
    }

    // An MPS tensor's storage is an MTLBuffer, handed out by torch's MPS
    // allocator as the storage's data pointer; the tensor starts at its
    // storage offset within it.
    id<MTLBuffer> buffer_of(const at::Tensor &t)
    {
      return __builtin_bit_cast(id<MTLBuffer>, t.storage().data());
    }

    NSUInteger offset_of(const at::Tensor &t)
    {
      return static_cast<NSUInteger>(t.storage_offset() * t.element_size());
    }

  } // namespace

  void launch(KernelSource source, const std::string &tail, std::initializer_list<KernelArg> args,
              uint64_t x, uint64_t y, uint64_t z)
  {
    for (const KernelArg &a : args)
      TORCH_INTERNAL_ASSERT(a.tensor == nullptr || a.tensor->is_mps(),
                            "mptorch: an MPS kernel was handed a tensor on ", a.tensor->device());
    id<MTLComputePipelineState> pipeline = pipeline_for(source, tail);

    // The threadgroup: one SIMD group wide along x, where a GEMM's adjacent
    // threads read adjacent columns of B, and as tall as the pipeline allows
    // up to 8 rows, which is 256 threads, never wider than the grid.
    const uint64_t width = pipeline.threadExecutionWidth;
    const uint64_t most = pipeline.maxTotalThreadsPerThreadgroup;
    const uint64_t tx = std::min<uint64_t>(x, source == KernelSource::Gemm ? width : most);
    const uint64_t ty = std::min<uint64_t>({y, std::max<uint64_t>(most / tx, 1), 8});
    const MTLSize grid = MTLSizeMake(x, y, z);
    const MTLSize group = MTLSizeMake(tx, ty, 1);
    const std::vector<KernelArg> bound(args);

    at::mps::MPSStream *stream = at::mps::getCurrentMPSStream();
    dispatch_sync(stream->queue(), ^() {
      @autoreleasepool
      {
        id<MTLComputeCommandEncoder> encoder = stream->commandEncoder();
        [encoder setComputePipelineState:pipeline];
        for (NSUInteger i = 0; i < bound.size(); ++i)
        {
          const KernelArg &a = bound[i];
          if (a.tensor != nullptr)
            [encoder setBuffer:buffer_of(*a.tensor) offset:offset_of(*a.tensor) atIndex:i];
          else
            [encoder setBytes:a.bytes length:a.size atIndex:i];
        }
        [encoder dispatchThreads:grid threadsPerThreadgroup:group];
      }
    });
  }

  const char *metal_storage_type(at::ScalarType t, const char *op)
  {
    switch (t)
    {
    case at::kFloat:
      return "float";
    case at::kHalf:
      return "half";
    case at::kBFloat16:
      return "bfloat";
    default:
      TORCH_CHECK(false, op, ": expected a float32, float16 or bfloat16 tensor on MPS, got ", t,
                  " (MPS has no float64, so a binary64 carrier is the CPU's and CUDA's only)");
    }
  }

  const char *metal_round_mode(int64_t rm)
  {
    static const char *const names[] = {"RoundMode::RNE", "RoundMode::RNA", "RoundMode::RU",
                                        "RoundMode::RD",  "RoundMode::RZ",  "RoundMode::RO",
                                        "RoundMode::SR"};
    TORCH_INTERNAL_ASSERT(rm >= 0 && rm < 7, "mptorch: ", rm, " is not a RoundMode");
    return names[rm];
  }

} // namespace mptorch_mps
